name:  CI Workflow 

on:
  push:
    branches:
      - '*'  # Se ejecuta en cualquier push a cualquier rama
  pull_request:
    branches:
      - '*'  # También se ejecuta en cualquier pull request a cualquier rama

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Ejecutar Flask 
        run: |
          export FLASK_APP=app.py  
          flask run --host=0.0.0.0 --port=5000  
        env:
          FLASK_APP: app.py  # Ajusta si tu archivo Flask tiene otro nombre
        continue-on-error: true  # No falla si el servidor Flask no puede iniciar
